apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
     nodePort: 30300
     name: postgres
  selector:
   app: postgres